### ISSUE TITLE
Need the Ability to give me the best promotions

### ISSUE THREAD

**Issue by AnkitaVK1997** [devops-summer22-promotions/promotions#10]
**As a** ... User
**I need** ... see the best deals/ promotions/discounts for my product/products
**So that** ... I buy products with max discount.

### Details and assumptions

* If I have certain no. of items in my cart, while checking out, I should get to apply the best promotions on to my cart to get the best discounts.

### Acceptance criteria

```gherkin
Given [some initial state]
When [some event]
Then [some measurable outcome]
```

**Comment by cs79** [comment]
Closing this issue as it was opened before we had delineated the specific functionality required for our microservice. More specific stories for CRUD / List All / Query / Cancel functionality supersede this more generic story.
