### ISSUE TITLE
Creating a relational database 

### ISSUE THREAD

**Issue by AnkitaVK1997** [devops-summer22-promotions/promotions#13]
**As a** ... software developer
**I need** ... a Relational Database 
**So that** ... I could have a clear idea about how to manage my data

### Details and assumptions

*  we can use MySQL

### Acceptance criteria
* database normalization rules must be followed

```gherkin
Given [some initial state]
When [some event]
Then [some measurable outcome]
```

**Comment by bisectracky** [comment]
this feature should support various scenarios that requires indicating relations between data, including specifying which promotions that a customer are registered with.

**Comment by cs79** [comment]
this appears to be handled by SQLAlchemy + the postgres docker container in the provided starter code; once the schema is defined, the tables are created and can be populated by the methods in the Promotion model
