### ISSUE TITLE
Need ability to create various kinds of promotions

### ISSUE THREAD

**Issue by cs79** [devops-summer22-promotions/promotions#3]
**As a** marketing manager
**I need** the ability to create different kinds of promotions
**So that** I can collect data to help our organization increase sales

### Details and assumptions

* Promotion creation will be done via POST requests to a Flask API
* The resource route may depend on the type of promotion, e.g. `/promotions/<type>`
* This implies we may want multiple user stories later for creating various types of promotions and the rationale for each
* At a minimum, the created promotion should have a validity window (e.g. "active start date" + "active end date" fields)
* Other features of the promotion depend on the type (e.g. "buy one get one free" or percentage discounts, bundled items, etc.)
* The promotions will be associated with a unique ID

### Acceptance criteria

```gherkin
Given [some initial state]
When [some event]
Then [some measurable outcome]
```

**Comment by bisectracky** [comment]
We would better also specify a id/value to identify a certain promotion when it was created.

**Comment by cs79** [comment]
working on this in tandem with schema design to give us a start that we can build the other CRUD routes off of

**Comment by cs79** [comment]
handled by https://github.com/devops-summer22-promotions/promotions/pull/18
