### ISSUE TITLE
Need CI pipeline to run unit tests (TDD) when making changes to master

### ISSUE THREAD

**Issue by cs79** [devops-summer22-promotions/promotions#33]
**As a** developer
**I need** TDD unit tests to be run automatically when pushing to or opening a PR for master
**So that** I can have some assurance that changes to master have not broken existing functionality that passes those tests

### Details and assumptions

* CI tests will be run using GitHub Actions
* There will be a file `.github/workflows/tdd.yml` added to this repository and configured to run these tests
* Tests themselves will be PyUnit tests
* Test coverage should not decrease in order for the changes to master to be accepted

### Acceptance criteria

```gherkin
Given a proposed change to the master branch
When that change is attempted to be merged, or has a PR opened for it
Then GitHub Actions will automatically run the TDD unit test suite for that change
```

**Comment by bisectracky** [comment]
Are we going to use PyUnit?

**Comment by cs79** [comment]
I would presume so, just because that is the framework we have used so far. I'll add this to the assumptions.

**Comment by cs79** [comment]
Assigning this to Sprint 2 as it will make our lives easier to have it done earlier.
