### ISSUE TITLE
Need IBM Cloud accounts for developers

### ISSUE THREAD

**Issue by cs79** [devops-summer22-promotions/promotions#36]
**As a** developer
**I need** an IBM Cloud account
**So that** I can deploy our microservice as part of a Kubernetes orchestration on the cloud

### Details and assumptions

* Each developer will need an account
* One developer will need to invite the rest of the team to their account
* Instructions on how to do this will be provided

### Acceptance criteria

```gherkin
Given [some initial state]
When [some event]
Then [some measurable outcome]
```

**Comment by bisectracky** [comment]
I will register an account for our team.

**Comment by cs79** [comment]
Assigning this to Sprint 2 as we will need this for today.

**Comment by cs79** [comment]
As of this afternoon I've now set up my own IBM Cloud account. Once the rest of the team has them, we can add everyone to a group.

**Comment by AnkitaVK1997** [comment]
I have set it up too, but with a different email(ankitakottur@nyu.edu)

**Comment by bisectracky** [comment]
I set with my email (zihao.ding@nyu.edu)

**Comment by MalikYang9636** [comment]
Have set it up: zy2226@nyu.edu

**Comment by happydl** [comment]
Mine is dl4430@nyu.edu

**Comment by cs79** [comment]
Instructions on how to invite everyone have been posted to Brightspace as of today

**Comment by bisectracky** [comment]
I will take a look now

**Comment by cs79** [comment]
I have added all users to an access group called "DevOps Class" on IBM Cloud using the emails provided above -- if anyone doesn't see an invite, let me know and I can sort it out.
