### ISSUE TITLE
Create a database model and schema

### ISSUE THREAD

**Issue by AnkitaVK1997** [devops-summer22-promotions/promotions#4]
**As a** ...Software Developer 
**I need** ...to create a database model and schema
**So that** ... can keep a track of all the promotions

### Details and assumptions

* Should give me a list of all promotions
* Should give me a list of the description of each promotion
* Should have a promo code that is unique
* Should have a start_date and an end_date
* Might have the product list for each promotion

### Acceptance criteria

```gherkin
Given [some initial state]
When [some event]
Then [some measurable outcome]
```

**Comment by cs79** [comment]
we can include the initial schema design as part of Sprint 1, with the assumption that it will likely evolve as we go

**Comment by cs79** [comment]
going to start working on this so i can put in an initial route to test things out -- schema subject to change based on what people think the various types of promotions we support should be

**Comment by cs79** [comment]
Added a commit on a feature branch which introduces a preliminary schema just to have something to work with -- we can change this as desired: https://github.com/devops-summer22-promotions/promotions/commit/d9d70be7245b0ff6a13b327d122aacb1dc7a36e0

**Comment by cs79** [comment]
handled by schema in https://github.com/devops-summer22-promotions/promotions/pull/17
