### ISSUE TITLE
Refactor your micro service to use Flask-RESTX

### ISSUE THREAD

**Issue by happydl** [devops-summer22-promotions/promotions#49]
**As** a developer
**I need** refactor the micro service to use Flask-RESTX
**So that** I can use Swagger to document the code

### Details and assumptions

* Make sure that all HTTP errors return json error messages and not
html
* Will actually be able to delete most of the
error_handlers.py file because Flask-RESTX will handle most of
these errors for you

### Acceptance criteria

```gherkin
Given The code is refactored
When service is tested
Then test cases still work as expected
```

**Comment by cs79** [comment]
Individual work units for this task are now divided into stories #68-74; once those stories are completed, this story may be considered "Done".
