### ISSUE TITLE
Need the ability to update a promotion.

### ISSUE THREAD

**Issue by AnkitaVK1997** [devops-summer22-promotions/promotions#5]
**As a** ...marketing manager
**I need** ... to be able to update a promotion
**So that** ...a promotion can be changed if needed

### Details and assumptions

* Should be able to update a promotion with respect to the ID of the promotion.

### Acceptance criteria

```gherkin
Given [some initial state]
When [some event]
Then [some measurable outcome]
```

**Comment by cs79** [comment]
perhaps we should make this a story for a "marketing manager" or some such ? i think the assumption was that the core service functionality would be used by someone in the business outside of the dev team. (rest of the story looks good!)
