### ISSUE TITLE
Provide Swagger documentation

### ISSUE THREAD

**Issue by happydl** [devops-summer22-promotions/promotions#50]
**As a** developer
**I need** provide Swagger documentation
**So that** I can have working and accurate Swagger docs

### Details and assumptions

* The documentation API must be available at: /apidocs/
* Ensure that Swagger docs work correctly and specify the data model

### Acceptance criteria

```gherkin
Given Swagger documentation is added
When visit Swagger documentation site
Then I can explore the API and data model specification
```

**Comment by cs79** [comment]
It is possible that this will be mostly incidentally implemented by the migration to Flask-RESTX, but we need to make sure this endpoint properly serves up the documentation.
