### ISSUE TITLE
Need Kubernetes configurations added to shared dev container

### ISSUE THREAD

**Issue by cs79** [devops-summer22-promotions/promotions#53]
**As a** developer
**I need** Kubernetes configurations added to the shared development container
**So that** the whole team can develop in a reproducible environment that mirrors our cloud deployment environment as closely as possible

### Details and assumptions

* Need to add metadata deployment files so that Kubernetes knows how to deploy the application

### Acceptance criteria

```gherkin
Given kubernetes configurations are duly set
When the configuration parameters and information can be verified on IBM cloud
Then whole team can develop in a reproducible environment 
```

**Comment by bisectracky** [comment]
modify acceptance criteria
