### ISSUE TITLE
Build an automated Continuous Delivery Pipeline in the Cloud

### ISSUE THREAD

**Issue by bisectracky** [devops-summer22-promotions/promotions#55]
**As** a developer
**I need** building an automated Continuous Delivery Pipeline in the Cloud
**So that** I can build a more complete CI/CD procedures for our project per agile requirement

### Details and assumptions

* Make sure that all HTTP errors return json error messages and not
html
* Will actually be able to delete most of the error_handlers.py file because Flask-RESTX will handle most of
these errors for you
* Set up the DevOps Continuous Delivery Pipeline in IBM Cloud to build and deploy your project when the master branch changes.
* Connect this DevOps pipeline to the GitHub repository for your project via a webhook. The owner of the repo must do this.
* Your Pipeline must have 4 stages: Build, Deploy, Test, Production
* Add a Unit Test Job to the Build Stage of the pipeline to run your units tests with nosetests
* Add a Dev Deployment Stage to the pipeline to build your Docker container and deploy to your dev namespace if the unit tests pass
* Add a Integration Test Stage to the pipeline to run your integration tests with behave against the Dev deployment
* Add a Production Deploy Stage to the pipeline to deploy to the prod namespace if all of the integration tests pass.
* Write Stories (as Github Issues) to plan the work needed to create the necessary integrations and add them to your Backlog.
* Move these Stories through the ZenHub Kanban board as you work on them just like you did in homework 1

### Acceptance criteria

```gherkin
Given The CD pipeline is built in the Cloud
When a commit is submitted to the master branch on our GitHub repo that runs the TDD unit tests
Then our service would be successful deployed to our Dev space
```

**Comment by cs79** [comment]
If we find a good way to break this story up we can do so, though it is probably OK to leave as-is with a larger story point estimate, too.

**Comment by cs79** [comment]
Individual work units for this task are now divided into stories #76-79; once those stories are completed, this story may be considered "Done".
