### ISSUE TITLE
Working as self-managing agile team

### ISSUE THREAD

**Issue by bisectracky** [devops-summer22-promotions/promotions#56]
**As a** ... agile team member
**I need** ... make sure that our team works in the form of a self-managing agile team
**So that** ... reach the goal of finishing this project as required by course criteria

### Details and assumptions
Add a Query route and an Action route to your microservice
Add Continuous Integration to every Pull Request
Deploy to the public Cloud
Implement a User Interface with Automated BDD Testing
Refactor using Flask-RESTX and Swagger
Build an automated Continuous Delivery Pipeline in the Cloud
* ...

### Acceptance criteria

```gherkin
Given all the aforementioned assumptions were satisfied.
When our agile workflow was tested properly working
Then we may confirm that we reach the goal of working as self-managing agile team.
```

**Comment by cs79** [comment]
This story may need to be split apart / rewritten; much of the things listed in details / assumptions here are covered by other stories already.

**Comment by cs79** [comment]
closing this issue as the details here are all covered in various stories for the corresponding requirements
