### ISSUE TITLE
Need ability to query promotions with filters

### ISSUE THREAD

**Issue by happydl** [devops-summer22-promotions/promotions#7]
**As a** marketing manager
**I need** the ability to query promotions with custom filters
**So that** I can inspect current promotions in the system.

### Details and assumptions

* Promotion query will be done via GET requests to a Flask API
* The URL should be `/promotions?<condition>=<value>`
* The API Should support different conditions e.g. `/promotions?create-date=6-9-2022&is-active=true`

### Acceptance criteria

```gherkin
Given [some initial state]
When [some event]
Then [some measurable outcome]
```

**Comment by cs79** [comment]
certain basic filtering (e.g. name, type) is already handled by our model implementation

**Comment by cs79** [comment]
This should be implemented on the "list promotions" route to satisfy the requirement for Sprint 2.
