### ISSUE TITLE
Set up Deploy stage in CI/CD pipeline on IBM Cloud

### ISSUE THREAD

**Issue by cs79** [devops-summer22-promotions/promotions#77]
**As a** developer
**I need** the automated CI/CD pipeline to run a deployment to the `dev` namespace every time I push changes to IBM Cloud
**So that** I can test that the application still deploys properly and is set up for BDD tests before deploying any changes to production

### Details and assumptions

* This story is part of coverage for #55; assumptions from that story apply here as well.
* The deploy stage should deploy our microservice to the `dev` namespace on IBM Cloud

### Acceptance criteria

```gherkin
Given the deploy stage is set up
When I push changes to the application
Then the deploy stage of the pipeline will deploy the application to the `dev` namespace on IBM Cloud
```

**Comment by cs79** [comment]
deploy stage is now passing with custom script to deploy into `dev` at port 31001 courtesy of professor Rofrano

**Comment by bisectracky** [comment]
Sounds good, is this the final port for `dev` ?

**Comment by cs79** [comment]
indeed it is :) when we set up `prod` we can presumably use a similar script, just need to change the namespace and specify the nodeport as 31002; currently stuck on the test stage of the CI/CD pipeline though
