### ISSUE TITLE
Filtering should be done on database side

### ISSUE THREAD

**Issue by cs79** [devops-summer22-promotions/promotions#80]
The querying filters should be applied on the database (model) side, not on the API (routes) side -- large sets of database entries, the latter is not feasible. New `find_by_X` functionality should be added to the `models.py` file to cover our filtering conditions, and these methods should be called as applicable by the API.

**Comment by bisectracky** [comment]
Can this be closed now?

**Comment by cs79** [comment]
nobody seems to have picked this one up so i assume no one has worked on it yet
